#############################################################################
# Makefile for building: sMonitor
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  sMonitor.pro
# Template: app
# Command: /root/yjz_wkspace/buildroot/output/host/usr/bin/qmake -spec devices/linux-buildroot-g++ CONFIG+=debug -o Makefile sMonitor.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /root/yjz_wkspace/buildroot/output/host/usr/bin/arm-cortex_a9-linux-gnueabi-gcc
CXX           = /root/yjz_wkspace/buildroot/output/host/usr/bin/arm-cortex_a9-linux-gnueabi-g++
DEFINES       = -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os --sysroot=/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os --sysroot=/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I. -I/usr/local/arm/opencv-arm/include -I/usr/local/arm/opencv-arm/include/opencv -I/usr/local/arm/opencv-arm/include/opencv2 -isystem /root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5 -isystem /root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimediaWidgets -isystem /root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimedia -isystem /root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtWidgets -isystem /root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtGui -isystem /root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtNetwork -isystem /root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtCore -I. -I. -I/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++
QMAKE         = /root/yjz_wkspace/buildroot/output/host/usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = sMonitor1.0.0
DISTDIR = /opt/backup/sMonitor/.tmp/sMonitor1.0.0
LINK          = /root/yjz_wkspace/buildroot/output/host/usr/bin/arm-cortex_a9-linux-gnueabi-g++
LFLAGS        = --sysroot=/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot
LIBS          = $(SUBLIBS) /usr/local/arm/opencv-arm/lib/libopencv_highgui.so /usr/local/arm/opencv-arm/lib/libopencv_core.so /usr/local/arm/opencv-arm/lib/libopencv_imgproc.so /usr/local/arm/opencv-arm/lib/libopencv_imgcodecs.so /usr/local/arm/opencv-arm/lib/libopencv_video.so /usr/local/arm/opencv-arm/lib/libopencv_videoio.so /usr/local/arm/opencv-arm/lib/libopencv_objdetect.so /usr/local/arm/opencv-arm/lib/libopencv_face.so `pkg-config --cflags --libs opencv` -lQt5MultimediaWidgets -lQt5Multimedia -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lrt -ldl -lpthread 
AR            = /root/yjz_wkspace/buildroot/output/host/usr/bin/arm-cortex_a9-linux-gnueabi-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /root/yjz_wkspace/buildroot/output/host/usr/bin/arm-cortex_a9-linux-gnueabi-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		menu.cpp \
		fops.cpp \
		steng.cpp \
		model.cpp \
		fileIndex.cpp \
		click_lable.cpp \
		fullShow.cpp \
		autoptz.cpp \
		mythread.cpp \
		cmythread.cpp qrc_images.cpp \
		moc_menu.cpp \
		moc_fops.cpp \
		moc_steng.cpp \
		moc_model.cpp \
		moc_fileIndex.cpp \
		moc_click_lable.cpp \
		moc_fullShow.cpp \
		moc_mythread.cpp \
		moc_cmythread.cpp
OBJECTS       = main.o \
		menu.o \
		fops.o \
		steng.o \
		model.o \
		fileIndex.o \
		click_lable.o \
		fullShow.o \
		autoptz.o \
		mythread.o \
		cmythread.o \
		qrc_images.o \
		moc_menu.o \
		moc_fops.o \
		moc_steng.o \
		moc_model.o \
		moc_fileIndex.o \
		moc_click_lable.o \
		moc_fullShow.o \
		moc_mythread.o \
		moc_cmythread.o
DIST          = fileIndex.o \
		click_lable.o \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/spec_pre.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/shell-unix.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/unix.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/linux.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/gcc-base.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/gcc-base-unix.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/g++-base.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/g++-unix.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/qdevice.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/device_config.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/common/linux_device_pre.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/common/linux_device_post.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/qconfig.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_bluetooth.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_concurrent.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_concurrent_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_core.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_core_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_dbus.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_dbus_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_declarative.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_declarative_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_gui.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_gui_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_multimedia.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_multimedia_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_network.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_network_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_nfc.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_nfc_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_printsupport.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_printsupport_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_qml.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_qml_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_script.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_script_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_scripttools.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_scripttools_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_sensors.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_sensors_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_serialport.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_serialport_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_sql.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_sql_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_svg.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_svg_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_testlib.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_testlib_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_widgets.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_widgets_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_xml.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_xml_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/qt_functions.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/qt_config.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++/qmake.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/spec_post.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/exclusive_builds.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/default_pre.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/resolve_config.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/default_post.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/warn_on.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/qt.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/resources.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/moc.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/uic.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/unix/thread.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/testcase_targets.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/exceptions.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/yacc.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/lex.prf \
		sMonitor.pro menu.h \
		fops.h \
		steng.h \
		model.h \
		fileIndex.h \
		click_lable.h \
		fullShow.h \
		ui_fileIndex.h \
		autoptz.h \
		mythread.h \
		cmythread.h main.cpp \
		menu.cpp \
		fops.cpp \
		steng.cpp \
		model.cpp \
		fileIndex.cpp \
		click_lable.cpp \
		fullShow.cpp \
		autoptz.cpp \
		mythread.cpp \
		cmythread.cpp
QMAKE_TARGET  = sMonitor
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = sMonitor


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_menu.h ui_fops.h ui_model.h ui_fullShow.h ui_fileIndex.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sMonitor.pro /root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++/qmake.conf /root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/spec_pre.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/shell-unix.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/unix.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/linux.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/gcc-base.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/gcc-base-unix.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/g++-base.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/g++-unix.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/qdevice.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/device_config.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/common/linux_device_pre.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/common/linux_device_post.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/qconfig.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_bluetooth.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_concurrent.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_concurrent_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_core.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_core_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_dbus.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_dbus_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_declarative.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_declarative_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_gui.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_gui_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_multimedia.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_multimedia_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_network.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_network_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_nfc.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_nfc_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_printsupport.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_printsupport_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_qml.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_qml_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_script.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_script_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_scripttools.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_scripttools_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_sensors.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_sensors_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_serialport.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_serialport_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_sql.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_sql_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_svg.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_svg_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_testlib.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_testlib_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_widgets.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_widgets_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_xml.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_xml_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/qt_functions.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/qt_config.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++/qmake.conf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/spec_post.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/exclusive_builds.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/default_pre.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/resolve_config.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/default_post.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/warn_on.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/qt.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/resources.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/moc.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/uic.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/unix/thread.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/testcase_targets.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/exceptions.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/yacc.prf \
		/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/lex.prf \
		sMonitor.pro \
		images.qrc \
		/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libQt5MultimediaWidgets.prl \
		/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libQt5Multimedia.prl \
		/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libQt5Network.prl \
		/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libQt5Core.prl \
		/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libQt5Gui.prl \
		/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libQt5Widgets.prl
	$(QMAKE) -spec devices/linux-buildroot-g++ CONFIG+=debug -o Makefile sMonitor.pro
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/spec_pre.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/shell-unix.conf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/unix.conf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/linux.conf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/gcc-base.conf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/gcc-base-unix.conf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/g++-base.conf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/common/g++-unix.conf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/qdevice.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/device_config.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/common/linux_device_pre.conf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/common/linux_device_post.conf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/qconfig.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_bluetooth.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_bluetooth_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_bootstrap_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_concurrent.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_concurrent_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_core.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_core_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_dbus.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_dbus_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_declarative.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_declarative_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_gui.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_gui_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_multimedia.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_multimedia_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_multimediawidgets.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_network.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_network_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_nfc.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_nfc_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_platformsupport_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_printsupport.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_printsupport_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_qml.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_qml_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_script.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_script_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_scripttools.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_scripttools_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_sensors.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_sensors_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_serialport.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_serialport_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_sql.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_sql_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_svg.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_svg_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_testlib.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_testlib_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_widgets.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_widgets_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_xml.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_xml_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_xmlpatterns.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/qt_functions.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/qt_config.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++/qmake.conf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/spec_post.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/exclusive_builds.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/default_pre.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/resolve_config.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/default_post.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/warn_on.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/qt.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/resources.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/moc.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/uic.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/unix/thread.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/testcase_targets.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/exceptions.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/yacc.prf:
/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/features/lex.prf:
sMonitor.pro:
images.qrc:
/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libQt5MultimediaWidgets.prl:
/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libQt5Multimedia.prl:
/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libQt5Network.prl:
/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libQt5Core.prl:
/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libQt5Gui.prl:
/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libQt5Widgets.prl:
qmake: FORCE
	@$(QMAKE) -spec devices/linux-buildroot-g++ CONFIG+=debug -o Makefile sMonitor.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents menu.h fops.h steng.h model.h fileIndex.h click_lable.h fullShow.h ui_fileIndex.h autoptz.h mythread.h cmythread.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp menu.cpp fops.cpp steng.cpp model.cpp fileIndex.cpp click_lable.cpp fullShow.cpp autoptz.cpp mythread.cpp cmythread.cpp $(DISTDIR)/
	$(COPY_FILE) --parents menu.ui fops.ui model.ui fullShow.ui fileIndex.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		images/up.png \
		images/camera.png \
		images/reset.png \
		images/down.png \
		images/video.png \
		images/file.png \
		images/change.png \
		images/model.png \
		images/false.png \
		images/exit.png \
		images/right.png \
		images/menu.jpg \
		images/left.png
	/root/yjz_wkspace/buildroot/output/host/usr/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_header_make_all: moc_menu.cpp moc_fops.cpp moc_steng.cpp moc_model.cpp moc_fileIndex.cpp moc_click_lable.cpp moc_fullShow.cpp moc_mythread.cpp moc_cmythread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_menu.cpp moc_fops.cpp moc_steng.cpp moc_model.cpp moc_fileIndex.cpp moc_click_lable.cpp moc_fullShow.cpp moc_mythread.cpp moc_cmythread.cpp
moc_menu.cpp: fops.h \
		steng.h \
		model.h \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvdef.h \
		/usr/local/arm/opencv-arm/include/opencv2/cvconfig.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/hal/interface.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/version.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/base.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/opencv_modules.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ptr.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/neon_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/vsx_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/traits.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/matx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/saturate.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/fast_math.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/types.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/bufferpool.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/persistence.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/operations.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/utility.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/core_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/optim.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ovx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/videoio.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/videoio/videoio_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/core.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/face.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/predict_collector.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facerec.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemark.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemarkLBF.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemarkAAM.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/face_alignment.hpp \
		click_lable.h \
		fileIndex.h \
		fullShow.h \
		autoptz.h \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dnn.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dict.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/layer.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dnn.inl.hpp \
		mythread.h \
		cmythread.h \
		menu.h
	/root/yjz_wkspace/buildroot/output/host/usr/bin/moc $(DEFINES) -I/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++ -I/opt/backup/sMonitor -I/usr/local/arm/opencv-arm/include -I/usr/local/arm/opencv-arm/include/opencv -I/usr/local/arm/opencv-arm/include/opencv2 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimediaWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimedia -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtGui -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtNetwork -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtCore -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4 -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/arm-cortex_a9-linux-gnueabi -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/backward -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include-fixed -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include menu.h -o moc_menu.cpp

moc_fops.cpp: fops.h
	/root/yjz_wkspace/buildroot/output/host/usr/bin/moc $(DEFINES) -I/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++ -I/opt/backup/sMonitor -I/usr/local/arm/opencv-arm/include -I/usr/local/arm/opencv-arm/include/opencv -I/usr/local/arm/opencv-arm/include/opencv2 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimediaWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimedia -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtGui -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtNetwork -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtCore -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4 -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/arm-cortex_a9-linux-gnueabi -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/backward -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include-fixed -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include fops.h -o moc_fops.cpp

moc_steng.cpp: steng.h
	/root/yjz_wkspace/buildroot/output/host/usr/bin/moc $(DEFINES) -I/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++ -I/opt/backup/sMonitor -I/usr/local/arm/opencv-arm/include -I/usr/local/arm/opencv-arm/include/opencv -I/usr/local/arm/opencv-arm/include/opencv2 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimediaWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimedia -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtGui -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtNetwork -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtCore -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4 -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/arm-cortex_a9-linux-gnueabi -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/backward -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include-fixed -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include steng.h -o moc_steng.cpp

moc_model.cpp: model.h
	/root/yjz_wkspace/buildroot/output/host/usr/bin/moc $(DEFINES) -I/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++ -I/opt/backup/sMonitor -I/usr/local/arm/opencv-arm/include -I/usr/local/arm/opencv-arm/include/opencv -I/usr/local/arm/opencv-arm/include/opencv2 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimediaWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimedia -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtGui -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtNetwork -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtCore -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4 -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/arm-cortex_a9-linux-gnueabi -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/backward -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include-fixed -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include model.h -o moc_model.cpp

moc_fileIndex.cpp: fullShow.h \
		click_lable.h \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvdef.h \
		/usr/local/arm/opencv-arm/include/opencv2/cvconfig.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/hal/interface.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/version.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/base.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/opencv_modules.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ptr.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/neon_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/vsx_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/traits.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/matx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/saturate.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/fast_math.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/types.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/bufferpool.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/persistence.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/operations.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/utility.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/core_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/optim.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ovx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/videoio.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/videoio/videoio_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc.hpp \
		fileIndex.h
	/root/yjz_wkspace/buildroot/output/host/usr/bin/moc $(DEFINES) -I/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++ -I/opt/backup/sMonitor -I/usr/local/arm/opencv-arm/include -I/usr/local/arm/opencv-arm/include/opencv -I/usr/local/arm/opencv-arm/include/opencv2 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimediaWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimedia -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtGui -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtNetwork -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtCore -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4 -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/arm-cortex_a9-linux-gnueabi -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/backward -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include-fixed -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include fileIndex.h -o moc_fileIndex.cpp

moc_click_lable.cpp: click_lable.h
	/root/yjz_wkspace/buildroot/output/host/usr/bin/moc $(DEFINES) -I/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++ -I/opt/backup/sMonitor -I/usr/local/arm/opencv-arm/include -I/usr/local/arm/opencv-arm/include/opencv -I/usr/local/arm/opencv-arm/include/opencv2 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimediaWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimedia -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtGui -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtNetwork -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtCore -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4 -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/arm-cortex_a9-linux-gnueabi -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/backward -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include-fixed -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include click_lable.h -o moc_click_lable.cpp

moc_fullShow.cpp: fullShow.h
	/root/yjz_wkspace/buildroot/output/host/usr/bin/moc $(DEFINES) -I/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++ -I/opt/backup/sMonitor -I/usr/local/arm/opencv-arm/include -I/usr/local/arm/opencv-arm/include/opencv -I/usr/local/arm/opencv-arm/include/opencv2 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimediaWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimedia -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtGui -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtNetwork -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtCore -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4 -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/arm-cortex_a9-linux-gnueabi -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/backward -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include-fixed -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include fullShow.h -o moc_fullShow.cpp

moc_mythread.cpp: steng.h \
		autoptz.h \
		mythread.h
	/root/yjz_wkspace/buildroot/output/host/usr/bin/moc $(DEFINES) -I/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++ -I/opt/backup/sMonitor -I/usr/local/arm/opencv-arm/include -I/usr/local/arm/opencv-arm/include/opencv -I/usr/local/arm/opencv-arm/include/opencv2 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimediaWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimedia -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtGui -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtNetwork -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtCore -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4 -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/arm-cortex_a9-linux-gnueabi -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/backward -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include-fixed -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include mythread.h -o moc_mythread.cpp

moc_cmythread.cpp: steng.h \
		cmythread.h
	/root/yjz_wkspace/buildroot/output/host/usr/bin/moc $(DEFINES) -I/root/yjz_wkspace/buildroot/output/host/usr/mkspecs/devices/linux-buildroot-g++ -I/opt/backup/sMonitor -I/usr/local/arm/opencv-arm/include -I/usr/local/arm/opencv-arm/include/opencv -I/usr/local/arm/opencv-arm/include/opencv2 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5 -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimediaWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtMultimedia -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtWidgets -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtGui -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtNetwork -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include/qt5/QtCore -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4 -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/arm-cortex_a9-linux-gnueabi -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include/c++/4.7.4/backward -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/include-fixed -I/root/yjz_wkspace/buildroot/output/host/opt/ext-toolchain/arm-cortex_a9-linux-gnueabi/include -I/root/yjz_wkspace/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include cmythread.h -o moc_cmythread.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_menu.h ui_fops.h ui_model.h ui_fullShow.h ui_fileIndex.h
compiler_uic_clean:
	-$(DEL_FILE) ui_menu.h ui_fops.h ui_model.h ui_fullShow.h ui_fileIndex.h
ui_menu.h: menu.ui
	/root/yjz_wkspace/buildroot/output/host/usr/bin/uic menu.ui -o ui_menu.h

ui_fops.h: fops.ui
	/root/yjz_wkspace/buildroot/output/host/usr/bin/uic fops.ui -o ui_fops.h

ui_model.h: model.ui
	/root/yjz_wkspace/buildroot/output/host/usr/bin/uic model.ui -o ui_model.h

ui_fullShow.h: fullShow.ui \
		click_lable.h
	/root/yjz_wkspace/buildroot/output/host/usr/bin/uic fullShow.ui -o ui_fullShow.h

ui_fileIndex.h: fileIndex.ui
	/root/yjz_wkspace/buildroot/output/host/usr/bin/uic fileIndex.ui -o ui_fileIndex.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp menu.h \
		fops.h \
		steng.h \
		model.h \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvdef.h \
		/usr/local/arm/opencv-arm/include/opencv2/cvconfig.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/hal/interface.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/version.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/base.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/opencv_modules.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ptr.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/neon_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/vsx_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/traits.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/matx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/saturate.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/fast_math.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/types.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/bufferpool.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/persistence.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/operations.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/utility.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/core_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/optim.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ovx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/videoio.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/videoio/videoio_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/core.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/face.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/predict_collector.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facerec.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemark.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemarkLBF.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemarkAAM.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/face_alignment.hpp \
		click_lable.h \
		fileIndex.h \
		fullShow.h \
		autoptz.h \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dnn.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dict.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/layer.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dnn.inl.hpp \
		mythread.h \
		cmythread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

menu.o: menu.cpp menu.h \
		fops.h \
		steng.h \
		model.h \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvdef.h \
		/usr/local/arm/opencv-arm/include/opencv2/cvconfig.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/hal/interface.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/version.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/base.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/opencv_modules.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ptr.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/neon_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/vsx_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/traits.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/matx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/saturate.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/fast_math.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/types.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/bufferpool.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/persistence.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/operations.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/utility.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/core_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/optim.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ovx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/videoio.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/videoio/videoio_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/core.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/face.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/predict_collector.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facerec.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemark.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemarkLBF.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemarkAAM.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/face_alignment.hpp \
		click_lable.h \
		fileIndex.h \
		fullShow.h \
		autoptz.h \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dnn.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dict.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/layer.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dnn.inl.hpp \
		mythread.h \
		cmythread.h \
		ui_menu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menu.o menu.cpp

fops.o: fops.cpp fops.h \
		ui_fops.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fops.o fops.cpp

steng.o: steng.cpp steng.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o steng.o steng.cpp

model.o: model.cpp model.h \
		ui_model.h \
		menu.h \
		fops.h \
		steng.h \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvdef.h \
		/usr/local/arm/opencv-arm/include/opencv2/cvconfig.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/hal/interface.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/version.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/base.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/opencv_modules.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ptr.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/neon_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/vsx_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/traits.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/matx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/saturate.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/fast_math.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/types.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/bufferpool.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/persistence.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/operations.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/utility.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/core_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/optim.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ovx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/videoio.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/videoio/videoio_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/core.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/face.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/predict_collector.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facerec.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemark.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemarkLBF.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemarkAAM.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/face_alignment.hpp \
		click_lable.h \
		fileIndex.h \
		fullShow.h \
		autoptz.h \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dnn.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dict.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/layer.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dnn.inl.hpp \
		mythread.h \
		cmythread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o model.cpp

fileIndex.o: fileIndex.cpp fileIndex.h \
		fullShow.h \
		click_lable.h \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvdef.h \
		/usr/local/arm/opencv-arm/include/opencv2/cvconfig.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/hal/interface.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/version.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/base.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/opencv_modules.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ptr.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/neon_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/vsx_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/traits.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/matx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/saturate.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/fast_math.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/types.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/bufferpool.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/persistence.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/operations.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/utility.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/core_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/optim.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ovx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/videoio.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/videoio/videoio_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc.hpp \
		ui_fileIndex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileIndex.o fileIndex.cpp

click_lable.o: click_lable.cpp click_lable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o click_lable.o click_lable.cpp

fullShow.o: fullShow.cpp fullShow.h \
		ui_fullShow.h \
		click_lable.h \
		menu.h \
		fops.h \
		steng.h \
		model.h \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvdef.h \
		/usr/local/arm/opencv-arm/include/opencv2/cvconfig.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/hal/interface.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/version.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/base.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/opencv_modules.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ptr.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/neon_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/vsx_utils.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/traits.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/matx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/saturate.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/fast_math.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/types.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/bufferpool.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/mat.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/persistence.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/operations.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/utility.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/core_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/optim.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/core/ovx.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/videoio.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/highgui/highgui_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/types_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/videoio/videoio_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/core/core.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/imgproc.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/arm/opencv-arm/include/opencv2/face.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/predict_collector.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facerec.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemark.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemarkLBF.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/facemarkAAM.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/face/face_alignment.hpp \
		fileIndex.h \
		autoptz.h \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dnn.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dict.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/layer.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn.hpp \
		/usr/local/arm/opencv-arm/include/opencv2/dnn/dnn.inl.hpp \
		mythread.h \
		cmythread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fullShow.o fullShow.cpp

autoptz.o: autoptz.cpp autoptz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autoptz.o autoptz.cpp

mythread.o: mythread.cpp mythread.h \
		steng.h \
		autoptz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mythread.o mythread.cpp

cmythread.o: cmythread.cpp cmythread.h \
		steng.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmythread.o cmythread.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_menu.o: moc_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menu.o moc_menu.cpp

moc_fops.o: moc_fops.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fops.o moc_fops.cpp

moc_steng.o: moc_steng.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_steng.o moc_steng.cpp

moc_model.o: moc_model.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_model.o moc_model.cpp

moc_fileIndex.o: moc_fileIndex.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fileIndex.o moc_fileIndex.cpp

moc_click_lable.o: moc_click_lable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_click_lable.o moc_click_lable.cpp

moc_fullShow.o: moc_fullShow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fullShow.o moc_fullShow.cpp

moc_mythread.o: moc_mythread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mythread.o moc_mythread.cpp

moc_cmythread.o: moc_cmythread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmythread.o moc_cmythread.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

